name: Run tests
on:
  pull_request:
    branches:
      - master

permissions:
  checks: write
  contents: write
  statuses: write

jobs:

  run-gradle-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Get Chrome version
        run: chrome --version

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew clean test

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: build/allure-results
          retention-days: 20

      - name: Generate test report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: gradle-test-results
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: karltiirik.github.io/spock-restassured-allure/${{ github.run_number }}/

#  run-maven-tests:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: maven
#
#      - name: Set up Chrome
#        uses: browser-actions/setup-chrome@latest
#
#      - name: Get Chrome version
#        run: chrome --version
#
#      - name: Run tests with Maven
#        run: ./mvnw clean test
#
#      - name: Generate test report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: maven-test-results
#          path: target/surefire-reports/TEST-*.xml
#          reporter: java-junit
#          fail-on-error: true